0.2
logzio/logzio-lambda-extensions pull request #10
Opened 2021-11-09 10:47 UTC by mirii1994

This PR:
* Allow parsing log into fields, as raised by #9 
* Allow parsing a log that's a JSON into nested fields.
* Adds explanation about the above features to the readme (still a work in progress needs edit from the ux team)

2021-11-09 14:26 UTC, Doron-Bargo requested changes
Great work
Please see my comment
Also please add negative and positive tests for the Grok option

2021-11-09 14:26 UTC, Doron-Bargo commented on logzio-lambda-extensions-logs/go.mod
>  	github.com/logzio/logzio-go v1.0.2
Please upgrade to version 1.0.3

2021-11-14 06:58 UTC, Doron-Bargo approved these changes
Great work on the positive and negative tests

2021-11-14 06:59 UTC, Doron-Bargo commented
@YajB - can you check the Readme?

2021-11-14 09:53 UTC, Doron-Bargo commented
@nico-shishkin - can you go over the readme?

2021-11-16 11:34 UTC, nico-shishkin approved these changes

2021-11-16 12:39 UTC, merged